(function(){
  "use strict";
  var data=(window.DOUYIN_DATA||[]).slice();
  var accountDaily=(window.DOUYIN_DAILY||[]).slice();
  var $=function(s){return document.querySelector(s)},$$=function(s){return Array.from(document.querySelectorAll(s))};
  var fmt=function(n){return Number(n||0).toLocaleString("zh-CN")},sum=function(a,k){return a.reduce(function(t,x){return t+Number(x[k]||0)},0)};
  var pct=function(v){return (Number(v||0)*100).toFixed(2)+"%"};
  var dated=data.filter(function(x){return x.date}).sort(function(a,b){return a.date.localeCompare(b.date)});
  var latestContentDate=dated.length?dated[dated.length-1].date.slice(0,10):"",latestDailyDate=accountDaily.length?accountDaily[accountDaily.length-1].date:"";
  var latestDate=latestDailyDate>latestContentDate?latestDailyDate:latestContentDate,latestMonth=latestDate.slice(0,7),latestYear=Number(latestDate.slice(0,4)),cutoff=latestDate.slice(5,10);
  var current=data.filter(function(x){return x.year===latestYear}),previous=data.filter(function(x){return x.year===latestYear-1&&x.date.slice(5,10)<=cutoff});
  var latestDay=accountDaily.filter(function(x){return x.date===latestDate}),monthRows=accountDaily.filter(function(x){return x.date.slice(0,7)===latestMonth});
  var coveredMonths={};accountDaily.forEach(function(x){coveredMonths[x.date.slice(0,7)]=true});
  function annualValue(year,key){return sum(data.filter(function(x){return x.year===year&&!coveredMonths[x.date.slice(0,7)]}),key)+sum(accountDaily.filter(function(x){return Number(x.date.slice(0,4))===year}),key)}
  function yoy(a,b){if(!b)return "";var r=(a-b)/b*100;return '<small class="'+(r>=0?'up':'down')+'">同比'+(latestYear-1)+'年 '+(r>=0?'+':'')+r.toFixed(1)+'%</small>'}
  function metric(label,value,note){return '<div class="xhsMetric"><span>'+label+'</span><strong>'+fmt(value)+'</strong>'+(note||'<small>&nbsp;</small>')+'</div>'}
  var annualPlays=annualValue(latestYear,"plays"),annualInteractions=annualValue(latestYear,"interactions"),previousPlays=annualValue(latestYear-1,"plays"),previousInteractions=annualValue(latestYear-1,"interactions");
  $("#dyMetrics").innerHTML='<div class="xhsMetricRow dyAnnual">'+metric("发布内容",current.length)+metric("累计播放",annualPlays,yoy(annualPlays,previousPlays))+metric("累计互动",annualInteractions,yoy(annualInteractions,previousInteractions))+metric("新增关注",sum(current,"follows"),yoy(sum(current,"follows"),sum(previous,"follows")))+'</div><div class="xhsMetricRow dyPeriod">'+metric("最新日播放",sum(latestDay,"plays"),'<small>'+latestDate+'</small>')+metric("最新日互动",sum(latestDay,"interactions"),'<small>赞 / 评 / 分享</small>')+metric("本月播放",sum(monthRows,"plays"),'<small>'+Number(latestMonth.slice(5,7))+'月完整数据</small>')+metric("本月互动",sum(monthRows,"interactions"),'<small>赞 / 评 / 分享</small>')+'</div>';
  $("#dyDateRange").outerHTML='<div class="trendRange" id="dyTrendRange"><button data-range="30">近30天</button><button class="on" data-range="ytd">年初至今</button><button data-range="all">总览</button></div>';
  var trend=echarts.init($("#dyTrend"));function renderTrend(range){var start="";if(range==="30"){var d=new Date(latestDate+"T00:00:00");d.setDate(d.getDate()-29);start=d.toISOString().slice(0,10)}else if(range==="ytd")start=latestYear+"-01-01";var byDay={};dated.forEach(function(x){var day=x.date.slice(0,10);if((!start||day>=start)&&!coveredMonths[day.slice(0,7)])byDay[day]=(byDay[day]||0)+x.plays});accountDaily.forEach(function(x){if(!start||x.date>=start)byDay[x.date]=x.plays});var days=Object.keys(byDay).sort();trend.setOption({grid:{left:60,right:18,top:22,bottom:42},tooltip:{trigger:"axis",valueFormatter:function(v){return fmt(v)}},xAxis:{type:"category",data:days,axisTick:{show:false},axisLine:{lineStyle:{color:"#dddde3"}},axisLabel:{color:"#74747c",fontSize:11,hideOverlap:true}},yAxis:{type:"value",axisLabel:{color:"#8d8d95"},splitLine:{lineStyle:{color:"#f0f0f3"}}},series:[{name:"播放量",type:"line",smooth:.22,showSymbol:false,data:days.map(function(day){return byDay[day]}),lineStyle:{color:"#827690",width:1.7},areaStyle:{color:new echarts.graphic.LinearGradient(0,0,0,1,[{offset:0,color:"rgba(130,118,144,.18)"},{offset:1,color:"rgba(130,118,144,.01)"}])}}]},true)}$("#dyTrendRange").addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;$$("#dyTrendRange button").forEach(function(x){x.classList.remove("on")});b.classList.add("on");renderTrend(b.dataset.range)});renderTrend("ytd");
  var top=data.slice().sort(function(a,b){return b.plays-a.plays}).slice(0,6);$("#dyTopList").innerHTML=top.map(function(x,i){return '<article class="xhsTopCard"><span class="xhsTopRank">'+(i+1)+'</span><img class="xhsTopCover'+(x.hasRealCover?'':' dyPlaceholder')+'" src="'+x.cover+'" alt=""><div class="xhsTopInfo"><div class="xhsTopTitle">'+x.title+'</div><div class="xhsTopDate">'+x.date.slice(0,16)+' · 互动 '+fmt(x.interactions)+'</div></div><div class="xhsTopViews">'+fmt(x.plays)+'<small>播放</small></div></article>'}).join("");
  var yearChart=echarts.init($("#dyYearChart")),colors={2026:"#6f6489",2025:"#5f8581",2024:"#b08a58",2023:"#66809a",2022:"#a8757f"};
  function renderYear(){var selected=$("#dyYear").value,years=selected==="all"?[2022,2023,2024,2025,2026]:[Number(selected)],series=[];years.forEach(function(y){var arr=Array(12).fill(0);data.filter(function(x){return x.year===y&&!coveredMonths[x.date.slice(0,7)]}).forEach(function(x){arr[Number(x.date.slice(5,7))-1]+=x.plays});accountDaily.filter(function(x){return Number(x.date.slice(0,4))===y}).forEach(function(x){arr[Number(x.date.slice(5,7))-1]+=x.plays});series.push({name:y+"年",type:"bar",data:arr,itemStyle:{color:colors[y],borderRadius:[4,4,0,0]},barMaxWidth:24});series.push({name:y+"年趋势",type:"line",data:arr,smooth:.28,symbol:"circle",symbolSize:4,lineStyle:{color:colors[y],width:1.1},itemStyle:{color:colors[y]},z:5})});yearChart.setOption({grid:{left:62,right:18,top:58,bottom:40},legend:{top:8,right:14,type:"scroll",textStyle:{color:"#6e6e73",fontSize:11}},tooltip:{trigger:"axis"},xAxis:{type:"category",data:["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],axisTick:{show:false},axisLine:{lineStyle:{color:"#dddde3"}},axisLabel:{color:"#595962",fontSize:12,fontWeight:600}},yAxis:{type:"value",axisLabel:{color:"#8d8d95"},splitLine:{lineStyle:{color:"#f0f0f3"}}},series:series},true)}
  $("#dyYear").addEventListener("change",renderYear);renderYear();
  var page=1,pageSize=6,filter="all",sort="playDesc";var c=new Date(latestDate+"T00:00:00");c.setDate(c.getDate()-29);var cutoff30=c.getFullYear()+"-"+String(c.getMonth()+1).padStart(2,"0")+"-"+String(c.getDate()).padStart(2,"0");
  function filtered(){var q=$("#dySearch").value.trim().toLowerCase();var rows=data.filter(function(x){if(q&&!x.title.toLowerCase().includes(q))return false;if(filter==="30")return x.date.slice(0,10)>=cutoff30;if(filter==="month")return x.date.slice(0,7)===latestMonth;return true});rows.sort(function(a,b){if(sort==="timeDesc")return b.date.localeCompare(a.date);if(sort==="timeAsc")return a.date.localeCompare(b.date);if(sort==="playDesc")return b.plays-a.plays;if(sort==="playAsc")return a.plays-b.plays;return 0});return rows}
  function pagerMarkup(current,total){var parts=['<button data-page="prev" '+(current===1?'disabled':'')+'>‹</button>'];for(var i=1;i<=total;i++){if(i===1||i===total||Math.abs(i-current)<=2)parts.push('<button class="'+(i===current?'active':'')+'" data-page="'+i+'">'+i+'</button>');else if(parts[parts.length-1]!=="<span>…</span>")parts.push("<span>…</span>")}parts.push('<button data-page="next" '+(current===total?'disabled':'')+'>›</button>');return parts.join("")}
  function renderTable(){var rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages);var view=rows.slice((page-1)*pageSize,page*pageSize);$("#dyCount").textContent="";$("#dyBody").innerHTML=view.map(function(x){return '<tr><td><div class="xhsCell"><img class="xhsCover'+(x.hasRealCover?'':' dyPlaceholder')+'" src="'+x.cover+'" alt=""><span class="xhsTitle">'+x.title+'</span></div></td><td>'+x.date.replace(" ","<br>")+'</td><td>'+pct(x.completion)+'</td><td>'+pct(x.fiveSecCompletion)+'</td><td>'+pct(x.twoSecBounce)+'</td><td>'+x.avgDuration.toFixed(2)+'秒</td><td>'+fmt(x.plays)+'</td><td>'+fmt(x.likes)+'</td><td>'+fmt(x.comments)+'</td><td>'+fmt(x.shares)+'</td><td>'+fmt(x.collects)+'</td><td>'+fmt(x.homepageVisits)+'</td><td>'+fmt(x.follows)+'</td></tr>'}).join("");$("#dyPager").innerHTML='<span class="platformResultCount">共 '+rows.length+' 条</span><span class="platformPager">'+pagerMarkup(page,pages)+'</span><span class="platformPagerSpacer"></span>'}
  $("#dySearch").addEventListener("input",function(){page=1;renderTable()});$("#dySort").addEventListener("change",function(e){sort=e.target.value;page=1;renderTable()});$("#dyFilterSeg").addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;$$("#dyFilterSeg button").forEach(function(x){x.classList.remove("on")});b.classList.add("on");filter=b.dataset.f;page=1;renderTable()});$("#dyPager").addEventListener("click",function(e){var b=e.target.closest("button");if(!b||b.disabled)return;var v=b.dataset.page;if(v==="prev")page--;else if(v==="next")page++;else page=Number(v);renderTable();$("#dy-content").scrollIntoView({behavior:"smooth"})});renderTable();
  var topNav=$("nav button[data-target='dy-top-section']");if(topNav)topNav.remove();
  var navButtons=$$("nav button"),navSections=navButtons.map(function(b){return document.getElementById(b.dataset.target)}).filter(Boolean);
  navButtons.forEach(function(b){b.addEventListener("click",function(){var el=document.getElementById(b.dataset.target);if(el)el.scrollIntoView({behavior:"smooth"})})});
  function syncNav(){var marker=window.scrollY+Math.min(240,window.innerHeight*.3),active=navSections[0];navSections.forEach(function(section){if(section.offsetTop<=marker)active=section});if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-24)active=navSections[navSections.length-1];navButtons.forEach(function(b){b.classList.toggle("selected",active&&b.dataset.target===active.id)})}window.addEventListener("scroll",syncNav,{passive:true});syncNav();
  window.addEventListener("resize",function(){trend.resize();yearChart.resize()});
})();
