(function(){
  "use strict";
  var data=(window.XHS_DATA||[]).slice();
  var monthlyOverrides=window.XHS_MONTHLY_OVERRIDES||{};
  var legacyMonthly=window.XHS_LEGACY_MONTHLY||{};
  document.documentElement.style.setProperty("--accent","#d64a5e");
  document.documentElement.style.setProperty("--accent-soft","#fcecef");
  var $=function(s){return document.querySelector(s)};
  var $$=function(s){return Array.from(document.querySelectorAll(s))};
  var dySoon=$$(".platformRail .soon").find(function(x){return x.textContent.trim().indexOf("抖音")===0});if(dySoon){var dyLink=document.createElement("a");dyLink.href="douyin.html";dyLink.textContent="抖音号";dySoon.replaceWith(dyLink)}
  var wxSoon=$$(".platformRail .soon").find(function(x){return x.textContent.trim()==="公众号"});if(wxSoon){var wxLink=document.createElement("a");wxLink.href="wechat.html";wxLink.textContent="公众号";wxSoon.replaceWith(wxLink)}
  $(".account").innerHTML='<img src="logo-xiaohongshu.png" class="xhsHeaderLogo" alt="小红书"><span class="xhsHeaderText">运营数据</span>';
  var fmt=function(n){return Number(n||0).toLocaleString("zh-CN")};
  var sum=function(a,k){return a.reduce(function(t,x){return t+Number(x[k]||0)},0)};
  var dated=data.filter(function(x){return x.date}).sort(function(a,b){return a.date.localeCompare(b.date)});
  var latestYear=Math.max.apply(null,data.map(function(x){return x.year}));
  var latestDate=dated.length?dated[dated.length-1].date.slice(0,10):"";
  var latestMonth=latestDate.slice(0,7),cutoff=latestDate.slice(5);
  var current=data.filter(function(x){return x.year===latestYear});
  var previous=data.filter(function(x){return x.year===latestYear-1&&x.date&&x.date.slice(5,10)<=cutoff});
  var latestDay=data.filter(function(x){return x.date&&x.date.slice(0,10)===latestDate});
  var monthRows=data.filter(function(x){return x.date&&x.date.slice(0,7)===latestMonth});
  function monthValue(year,month,key){var ym=year+"-"+String(month).padStart(2,"0"),override=monthlyOverrides[ym],legacy=legacyMonthly[ym];if(override&&override[key]!=null)return Number(override[key]);if(legacy&&legacy[key]!=null)return Number(legacy[key]);return sum(data.filter(function(x){return x.date&&x.date.slice(0,7)===ym}),key)}
  function yearValue(year,key,maxMonth){var total=0;for(var m=1;m<=maxMonth;m++)total+=monthValue(year,m,key);return total}
  function yoy(currentValue,previousValue){if(!previousValue)return "";var rate=(currentValue-previousValue)/previousValue*100;return '<small class="'+(rate>=0?'up':'down')+'">同比'+(latestYear-1)+'年 '+(rate>=0?'+':'')+rate.toFixed(1)+'%</small>'}
  function metric(label,value,note){return '<div class="xhsMetric"><span>'+label+'</span><strong>'+fmt(value)+'</strong>'+(note||'<small>&nbsp;</small>')+'</div>'}
  var latestMonthNumber=Number(latestMonth.slice(5,7)),annualViews=yearValue(latestYear,"views",latestMonthNumber),annualInteractions=yearValue(latestYear,"interactions",latestMonthNumber),previousViews=yearValue(latestYear-1,"views",latestMonthNumber),previousInteractions=yearValue(latestYear-1,"interactions",latestMonthNumber);
  var annual=metric("发布内容",current.length)+metric("累计阅读",annualViews,yoy(annualViews,previousViews))+metric("累计互动",annualInteractions,yoy(annualInteractions,previousInteractions));
  var period=metric("最新日阅读",sum(latestDay,"views"),'<small>'+latestDate+'</small>')+metric("最新日互动",sum(latestDay,"interactions"),'<small>评论、点赞、收藏、分享</small>')+metric("本月阅读",monthValue(latestYear,latestMonthNumber,"views"),'<small>'+latestMonthNumber+'月完整增量</small>')+metric("本月互动",monthValue(latestYear,latestMonthNumber,"interactions"),'<small>评论、点赞、收藏、分享</small>');
  $("#xhsMetrics").innerHTML='<div class="xhsMetricRow annual">'+annual+'</div><div class="xhsMetricRow period">'+period+'</div>';
  $("#xhsDateRange").outerHTML='<div class="trendRange" id="xhsTrendRange"><button data-range="30">近30天</button><button class="on" data-range="ytd">年初至今</button><button data-range="all">总览</button></div>';
  var trend=echarts.init($("#xhsTrend"));
  function renderTrend(range){var start="";if(range==="30"){var d=new Date(latestDate+"T00:00:00");d.setDate(d.getDate()-29);start=d.toISOString().slice(0,10)}else if(range==="ytd")start=latestYear+"-01-01";var byDay={};dated.forEach(function(x){var day=x.date.slice(0,10);if(!start||day>=start)byDay[day]=(byDay[day]||0)+x.views});var days=Object.keys(byDay).sort();trend.setOption({grid:{left:56,right:18,top:22,bottom:42},tooltip:{trigger:"axis",valueFormatter:function(v){return fmt(v)}},xAxis:{type:"category",data:days,axisTick:{show:false},axisLine:{lineStyle:{color:"#dddde3"}},axisLabel:{color:"#74747c",fontSize:11,hideOverlap:true}},yAxis:{type:"value",axisLabel:{color:"#8d8d95"},splitLine:{lineStyle:{color:"#f0f0f3"}}},series:[{name:"阅读量",type:"line",smooth:.22,showSymbol:false,data:days.map(function(day){return byDay[day]}),lineStyle:{color:"#c95d70",width:1.7},areaStyle:{color:new echarts.graphic.LinearGradient(0,0,0,1,[{offset:0,color:"rgba(201,93,112,.16)"},{offset:1,color:"rgba(201,93,112,.01)"}])}}]},true)}
  $("#xhsTrendRange").addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;$$("#xhsTrendRange button").forEach(function(x){x.classList.remove("on")});b.classList.add("on");renderTrend(b.dataset.range)});renderTrend("ytd");

  var top=data.slice().sort(function(a,b){return b.views-a.views}).slice(0,6);
  $("#xhsTopList").innerHTML=top.map(function(x,i){return '<article class="xhsTopCard"><span class="xhsTopRank">'+(i+1)+'</span><img class="xhsTopCover" src="'+x.cover+'" alt=""><div class="xhsTopInfo"><div class="xhsTopTitle">'+x.title+'</div><div class="xhsTopDate">'+(x.date||x.year+"年")+' · 互动 '+fmt(x.interactions)+'</div></div><div class="xhsTopViews">'+fmt(x.views)+'<small>阅读</small></div></article>'}).join("");

  var yearChart=echarts.init($("#xhsYearChart"));
  var colors={2026:"#75648a",2025:"#a59ab1",2024:"#c2b8ca",2023:"#dad4df"};
  function renderYear(){var selected=$("#xhsYear").value;var years=selected==="all"?[2023,2024,2025,2026]:[Number(selected)];var series=[];years.forEach(function(y){var arr=Array(12).fill(0).map(function(_,i){return monthValue(y,i+1,"views")});series.push({name:y+"年",type:"bar",data:arr,itemStyle:{color:colors[y],borderRadius:[4,4,0,0]},barMaxWidth:26});series.push({name:y+"年趋势",type:"line",data:arr,smooth:.28,symbol:"circle",symbolSize:4,lineStyle:{color:colors[y],width:1.15,opacity:.9},itemStyle:{color:colors[y]},z:5})});yearChart.setOption({grid:{left:58,right:18,top:58,bottom:38},legend:{top:8,right:14,type:"scroll",textStyle:{color:"#6e6e73",fontSize:11}},tooltip:{trigger:"axis"},xAxis:{type:"category",data:["1月","2月","3月","4月","5月","6月","7月","8月","9月","10月","11月","12月"],axisTick:{show:false},axisLine:{lineStyle:{color:"#dddde3"}},axisLabel:{color:"#595962",fontSize:12,fontWeight:600}},yAxis:{type:"value",axisLabel:{color:"#8d8d95"},splitLine:{lineStyle:{color:"#f0f0f3"}}},series:series},true)}
  $("#xhsYear").addEventListener("change",renderYear);renderYear();

  $(".xhsFilters").innerHTML='<div class="seg" id="xhsFilterSeg"><button class="on" data-f="all">全部时间</button><button data-f="30">近30天</button><button data-f="month">本月</button></div><label class="xhsSearchField">搜索 <input id="xhsSearch" placeholder="内容关键词"></label><label class="xhsSortField">排序 <select id="xhsSort"><option value="timeDesc">时间降序</option><option value="timeAsc">时间升序</option><option value="readDesc">阅读量降序</option><option value="readAsc">阅读量升序</option></select></label>';
  var page=1,pageSize=6,tableFilter="all",tableSort="timeDesc";
  var latestDayObj=latestDate?new Date(latestDate+"T00:00:00"):new Date();latestDayObj.setDate(latestDayObj.getDate()-29);var cutoff30=latestDayObj.getFullYear()+"-"+String(latestDayObj.getMonth()+1).padStart(2,"0")+"-"+String(latestDayObj.getDate()).padStart(2,"0");
  function filtered(){var q=$("#xhsSearch").value.trim().toLowerCase();var rows=data.filter(function(x){if(q&&!x.title.toLowerCase().includes(q))return false;if(tableFilter==="30")return x.date&&x.date.slice(0,10)>=cutoff30;if(tableFilter==="month")return x.date&&x.date.slice(0,7)===latestMonth;return true});rows.sort(function(a,b){var ad=a.date||String(a.year),bd=b.date||String(b.year);if(tableSort==="timeDesc")return bd.localeCompare(ad);if(tableSort==="timeAsc")return ad.localeCompare(bd);if(tableSort==="readDesc")return b.views-a.views;if(tableSort==="readAsc")return a.views-b.views;return 0});return rows}
  function pagerMarkup(current,total){var parts=['<button data-page="prev" '+(current===1?'disabled':'')+'>‹</button>'];for(var i=1;i<=total;i++){if(i===1||i===total||Math.abs(i-current)<=2)parts.push('<button class="'+(i===current?'active':'')+'" data-page="'+i+'">'+i+'</button>');else if(parts[parts.length-1]!=="<span>…</span>")parts.push("<span>…</span>")}parts.push('<button data-page="next" '+(current===total?'disabled':'')+'>›</button>');return parts.join("")}
  function renderTable(){var rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages);var view=rows.slice((page-1)*pageSize,page*pageSize);$("#xhsCount").textContent="";$("#xhsBody").innerHTML=view.map(function(x){return '<tr><td><div class="xhsCell"><img class="xhsCover" src="'+x.cover+'" alt=""><span class="xhsTitle">'+x.title+'</span></div></td><td>'+(x.date||x.year+"年")+'</td><td>'+fmt(x.views)+'</td><td>'+fmt(x.interactions)+'</td><td>'+fmt(x.comments)+'</td><td>'+fmt(x.likes)+'</td><td>'+fmt(x.collects)+'</td><td>'+fmt(x.shares)+'</td></tr>'}).join("");$("#xhsPager").innerHTML='<span class="platformResultCount">共 '+rows.length+' 条</span><span class="platformPager">'+pagerMarkup(page,pages)+'</span><span class="platformPagerSpacer"></span>'}
  $("#xhsSearch").addEventListener("input",function(){page=1;renderTable()});$("#xhsSort").addEventListener("change",function(e){tableSort=e.target.value;page=1;renderTable()});$("#xhsFilterSeg").addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;$$("#xhsFilterSeg button").forEach(function(x){x.classList.remove("on")});b.classList.add("on");tableFilter=b.dataset.f;page=1;renderTable()});$("#xhsPager").addEventListener("click",function(e){var b=e.target.closest("button");if(!b||b.disabled)return;var v=b.dataset.page;if(v==="prev")page--;else if(v==="next")page++;else page=Number(v);renderTable();$("#xhs-content").scrollIntoView({behavior:"smooth"})});renderTable();
  var topNav=$('nav button[data-target="xhs-top-section"]');if(topNav)topNav.remove();
  var navButtons=$$('nav button'),navSections=navButtons.map(function(b){return document.getElementById(b.dataset.target)}).filter(Boolean);
  navButtons.forEach(function(b){b.addEventListener('click',function(){var el=document.getElementById(b.dataset.target);if(el)el.scrollIntoView({behavior:'smooth'})})});
  function syncNav(){var marker=window.scrollY+Math.min(240,window.innerHeight*.3),active=navSections[0];navSections.forEach(function(section){if(section.offsetTop<=marker)active=section});if(window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-24)active=navSections[navSections.length-1];navButtons.forEach(function(b){b.classList.toggle('selected',active&&b.dataset.target===active.id)})}window.addEventListener('scroll',syncNav,{passive:true});syncNav();
  window.addEventListener("resize",function(){trend.resize();yearChart.resize()});
})();
